# Generated by Django 3.2.4 on 2021-08-01 18:44

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0004_auto_20210730_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('image_URL', models.URLField(blank=True)),
                ('subtitulo', models.CharField(max_length=400)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('puntuacion', models.BigIntegerField(default=0)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.categoria')),
                ('distrito_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('recurso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='home.recurso')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.provincia'),
        ),
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('recurso_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('recurso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recurso')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criterio1', models.IntegerField(default=0)),
                ('criterio2', models.IntegerField(default=0)),
                ('criterio3', models.IntegerField(default=0)),
                ('criterio4', models.IntegerField(default=0)),
                ('criterio5', models.IntegerField(default=0)),
                ('recurso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recurso')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Categoría')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='home.categoria')),
            ],
            options={
                'verbose_name': 'Categoría Translation',
                'db_table': 'home_categoria_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
