# Generated by Django 3.2.4 on 2021-07-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_favorito_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='puntuacion',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='subtitulo',
            field=models.CharField(max_length=400),
        ),
    ]
