# Generated by Django 3.2.4 on 2021-07-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_recurso_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='puntuacion',
            field=models.BigIntegerField(default=0),
        ),
    ]
