# Generated by Django 3.2.4 on 2021-07-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_auto_20210722_1229'),
        ('home', '0007_alter_favorito_recurso_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('recurso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recurso')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('criterio1', models.IntegerField(default=0)),
                ('criterio2', models.IntegerField(default=0)),
                ('criterio3', models.IntegerField(default=0)),
                ('criterio4', models.IntegerField(default=0)),
                ('criterio5', models.IntegerField(default=0)),
                ('recurso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.recurso')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
        ),
    ]
